# Generated by Django 4.2.20 on 2025-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
