# Generated by Django 4.2.20 on 2025-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('c_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
