# Generated by Django 4.2.20 on 2025-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=40)),
                ('u_id', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
