# Generated by Django 4.2.20 on 2025-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('quandity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
