# Generated by Django 4.2.20 on 2025-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superindentent',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phn_no', models.IntegerField()),
            ],
            options={
                'db_table': 'superindentent',
                'managed': False,
            },
        ),
    ]
